# Generated by Django 3.0.3 on 2020-02-24 18:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=40)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('flag_admin', models.CharField(blank=True, max_length=1)),
                ('flag_blocked', models.CharField(blank=True, max_length=1)),
                ('flag_login', models.CharField(blank=True, max_length=1)),
            ],
            options={
                'unique_together': {('email', 'name')},
            },
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mangmentblog.person')),
                ('postCat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mangmentblog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangmentblog.post')),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mangmentblog.Comment')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mangmentblog.post')),
            ],
        ),
    ]
