# Generated by Django 3.0.3 on 2020-02-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangmentblog', '0003_auto_20200227_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifSender', models.CharField(max_length=50, verbose_name='Ur name')),
                ('notifContent', models.CharField(max_length=200, verbose_name='Objection details')),
            ],
        ),
    ]
