# Generated by Django 3.0.3 on 2020-03-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangmentblog', '0006_auto_20200301_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='open_img/'),
        ),
    ]
