# Generated by Django 3.0.3 on 2020-03-02 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mangmentblog', '0008_auto_20200301_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='note_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
